matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: '10'
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: docker
      language: generic

    - os: windows
      language: node_js
      node_js: "8"

cache:
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        apt-get update && apt-get install -y libudev-dev && yarn global add node-gyp && yarn dist
      else
        yarn dist
      fi
    fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
