const zh_en = {
  NewAccount: ['新增账户', 'new account'],
  Asset: ['资产', 'Assets'],
  ChainXAsset: ['ChainX资产', 'ChainX Asset'],
  DepositsMining: ['充值挖矿', 'Deposits Mining'],
  NominationsElections: ['投票选举', 'Nominations Elections'],
  DepositWithdrawalRecords: ['充提记录', 'Deposit & Withdrawal Records'],
  AssetTrustee: ['资产信托', 'Asset Trustee'],
  DEX: ['币币交易', 'DEX'],
  DAPP: ['DAPP专区', 'DAPP'],
  TradingRecord: ['交易记录', 'Trading Records'],
  Contact: ['联系人', 'Contact'],
  CrossChainAssets: ['跨链资产', 'Cross-chain Assets'],
  ValidatorNode: ['验证节点', 'Validator Node'],
  TrusteeNode: ['信托节点', 'Trustee Node'],
  StandbyNode: ['候选节点', 'Standby Node'],
  MyNominations: ['我的投票', 'My Nominations'],
  UpdateNode: ['更新节点', 'Update Node'],
  RegisterNode: ['注册节点', 'Register Node'],
  TrusteeSettings: ['信托设置', 'Trustee Settings'],
  SetupTrustee: ['设置信托', 'Setup Trustee'],
  WithdrawalList: ['提现列表', 'Withdrawal List'],
  WithdrawAmount: ['提现数量', 'Withdrawal Amount'],
  BuildMultiSigWithdrawal: ['构造多签提现', 'Build MultiSig Withdrawal'],
  OpenOrders: ['挂单列表', 'Open Orders'],
  LimitTrade: ['限价交易', 'Limit'],
  LatestTrade: ['最新成交', 'Latest'],
  CurrentOrder: ['当前委托', 'Open Orders'],
  HistoryOrder: ['历史委托', 'Order History'],
  AddressList: ['地址列表', 'Addresses'],
  AddAddress: ['添加地址', 'Add Address'],

  Name: ['名称', 'Name'],
  ShortName: ['简称', 'Short Name'],
  FreeBalance: ['可用余额', 'Available'],
  StakingReserved: ['投票冻结', 'Staking Reserved'],
  UnfreezeReserved: ['赎回冻结', ' Unfreeze Reserved'],
  DexReserved: ['交易冻结', 'Dex Reserved'],
  TotalBalance: ['总余额', 'Total Balance'],
  GetFreeCoin: ['领币', 'Get'],
  Transfer: ['转账', 'Transfer'],
  InnerChainTransfer: ['链内转账', 'Transfer'],
  OriginalChain: ['原链', 'Original Chain'],
  WithdrawalReserved: ['提现冻结', 'Withdrawal Reserved'],
  Deposit: ['充值', 'Deposit'],
  CrossChainDeposit: ['跨链充值', 'Deposit'],
  Withdraw: ['提现', 'Withdraw'],
  CrossChainWithdraw: ['跨链提现', 'Withdraw'],
  Mapping: ['映射', 'Mapping'],
  CrossChainMapping: ['跨链映射', 'Mapping'],
  ReceiveAddress: ['接收人地址', 'Receive Address'],
  ReceiptAddress: ['收款地址', 'Receipt address'],
  TransferAmount: ['转账数量', 'Transfer Amount'],
  Memo: ['备注', 'Memo'],
  PublicMultiSigTrusteeAddress: ['公共多签托管地址', 'Public MultiSig Trustee Address'],
  CopyMessage: ['复制信息', 'Copy'],
  RecommendedChannelNode: ['输入推荐渠道的节点名称 (选填)', 'Recommended Channel Node (optional)'],
  GetWithdrawFee: ['收取提现手续费', 'Required Fee'],

  CharacterLength: ['{length}个字符以内', 'Within {length} characters'],
  AddressFormatError: ['地址格式错误', 'Address format error'],
  BalanceNotEnough: ['余额不足', 'Balance not enough'],
  Required: ['必填', 'Required'],
  Confirm: ['确定', 'Confirm'],
  Skip: ['跳过', 'Skip'],
};

export const zh_CN = {};
export const en_US = {};
Object.getOwnPropertyNames(zh_en).forEach(key => {
  zh_CN[key] = zh_en[key][0];
  en_US[key] = zh_en[key][1];
});
