const zh_en = {
  NewAccount: ['新增账户', 'New Account'],
  AddAccount: ['添加账户', 'Add Account'],
  ForgetAccount: ['忘记账户', 'Forget Account'],
  ChangePassword: ['修改密码', 'Change Password'],
  ImportPrivateKey: ['导入私钥', 'Import Private Key'],
  PrivateKey: ['私钥', 'Private Key'],
  Import: ['导入', 'Import'],
  CompleteTheForm: ['请填写完整', 'Please complete the form'],
  ExportPrivateKey: ['导出私钥', 'Export Private Key'],
  ImportMnemonic: ['导入助记词', 'Import Mnemonic'],
  SettingPassword: ['设置密码', 'Set up password'],
  BackUpMnemonic: ['备份助记词', 'Back up the mnemonic'],
  WarmReminder: ['温馨提醒', 'Warm Reminder'],
  IHaveBackedUp: ['我已备份', 'I have backed up'],
  ValidateMnemonic: ['验证助记词', 'Validate Mnemonic'],
  AccountImportPrivateKeyNotFormat: ['私钥错误，请核对后重新输入', 'Private key error, please check and retransmit'],
  AccountImportMnemonicNotFormat: ['助记词错误，请核对后重新输入', 'Wrong Mnemonic, Please Check and Input Again'],
  AccountImportMnemonicNotEqual: ['助记词顺序错误，请核对后重新输入', 'Wrong Order for the Mnemonic, Please Try Again'],
  BackUpStep: ['返回上一步', 'Back to the previous step'],
  ConfirmMnemonicOrder: ['按顺序确认您的助记词', 'Input Your Mnemonic In Order'],
  InputMnemonicOrder: [
    '按顺序输入您的助记词，并以Tab键区分',
    'Enter your mnemonics in order and distinguish them with the Tab key',
  ],
  NotSavePrivateKeyAnyWhere: [
    '不要将您的私钥存储在您的电脑上，或者网上某处。任何能够访问您备份私钥的人就能取用您的资金。',
    "Don't store your private key on your computer or somewhere online. Anyone who has access to your backup private key can access your funds",
  ],

  Complete: ['完成', 'Complete'],
  Asset: ['资产', 'Assets'],
  ChainXAsset: ['ChainX资产', 'ChainX Asset'],
  DepositsMining: ['充值挖矿', 'Deposits Mining'],
  NominationsElections: ['投票选举', 'Staking'],
  DepositWithdrawalRecords: ['充提记录', 'Deposit & Withdrawal Records'],
  DepositRecords: ['充值记录', 'Deposit Records'],
  WithdrawalRecords: ['提现记录', 'Withdrawal Records'],
  AssetTrustee: ['资产信托', 'Trustees'],
  DEX: ['币币交易', 'DEX'],
  DAPP: ['DAPP专区', 'DAPP'],
  TradingRecord: ['交易记录', 'Tradings'],
  Contact: ['联系人', 'Contact'],
  CrossChainAssets: ['跨链资产', 'Cross-chain Assets'],
  ValidatorNode: ['验证节点', 'Validator'],
  TrusteeNode: ['信托节点', 'Trustee Node'],
  StandbyNode: ['候选节点', 'Standby'],
  MyNominations: ['我的投票', 'My Nominations'],
  UpdateNode: ['更新节点', 'Update Node'],
  RegisterNode: ['注册节点', 'Register Node'],
  TrusteeSettings: ['信托设置', 'Trustee Settings'],
  SetupTrustee: ['设置信托', 'Setup Trustee'],
  WithdrawalList: ['提现列表', 'Withdrawal List'],
  OriginalDataToSigned: ['待签原文', 'Original data to be signed'],
  WithdrawAmount: ['提现数量', 'Withdrawal Amount'],
  BuildMultiSigWithdrawal: ['构造多签提现', 'Build MultiSig Withdrawal'],
  OpenOrders: ['挂单列表', 'Open Orders'],
  LimitTrade: ['限价交易', 'Limit'],
  LatestTrade: ['最新成交', 'Latest'],
  CurrentOrder: ['当前委托', 'Open Orders'],
  HistoryOrder: ['历史委托', 'Order History'],
  AddressList: ['地址列表', 'Addresses'],
  AddAddress: ['添加地址', 'Add Address'],
  ChooseChain: ['选择链', 'Choose Chain'],
  LaunchTime: ['发起时间', 'Start Time'],
  ApplicationTime: ['申请时间', 'Application Date'],
  OriginalChainTradeID: ['原链交易ID', 'Original Chain ID'],
  Token: ['币种', 'Token'],
  Amount: ['数量', 'Amount'],
  Rank: ['排名', 'Ranking'],
  AssetType: ['资产种类', ' Asset Type'],
  TotalChainBalance: ['全链总余额', 'Total Balance'],
  MiningPower: ['挖矿算力', 'Mining Power'],
  EquivalentNominations: ['折合投票数', 'Equivalent'],
  JackpotBalance: ['奖池金额', 'Jackpot'],
  MyTotalBalance: ['我的总余额', 'My Total Balance'],
  UnclaimedDividend: ['待领利息', 'Unclaimed'],
  ClaimDividend: ['提息', 'Claim'],
  AccountAddress: ['账户地址', 'Address'],
  IntentionSelfNominated: ['节点抵押', 'Self-nominated'],
  TotalNomination: ['总得票数', 'Total Nomination'],
  Unfreeze: ['解冻', 'Unfreeze'],
  Inactive: ['已退选', 'Inactive'],
  UnfreezeLocked: ['赎回解冻', 'Unfreeze Locked'],
  Nominate: ['投票', 'Nominate'],
  IncreaseNomination: ['追加投票', 'Increase'],
  DecreaseNomination: ['赎回投票', 'Decrease'],
  SwitchNomination: ['切换投票', 'Switch'],
  NominateAmount: ['投票数量', 'Nominate Amount'],
  IncreaseAmount: ['追加数量', 'Increase Amount'],
  DecreaseAmount: ['赎回数量', 'Decrease Amount'],
  SwitchAmount: ['切换数量', 'Switch Amount'],
  IncreaseN: ['追加', 'Increase'],
  DecreaseN: ['赎回', 'Decrease'],
  SwitchN: ['切换', 'Switch'],
  NodeName: ['节点名称', 'Node Name'],
  NewNode: ['新节点', 'New Node'],
  FreezeBalance: ['冻结金额', 'In Order'],
  FactFilled: ['实际成交', 'Filled'],
  FilledPercent: ['成交率', 'Filled'],
  DeadTime: ['到期时间', 'DeadTime'],
  Time: ['时间', 'Date'],
  predict: ['预估', 'predict'],
  BlockAuthoringAddress: ['出块地址', 'Block Authoring Address'],
  OrderNumber: ['委托编号', 'Number'],
  TradingPair: ['交易对', 'Pair'],
  Direction: ['方向', 'Direction'],
  OrderPrice: ['委托价格', 'Order Price'],
  OrderAmount: ['委托数量', 'Order Amount'],
  Offer: ['报价', 'Offer'],
  CurrentChainID: ['本连交易ID', 'Trading ID'],
  Account: ['账户', 'Account'],

  Name: ['名称', 'Name'],
  ShortName: ['简称', 'Short Name'],
  FreeBalance: ['可用余额', 'Free'],
  Balance: ['金额', 'Amount'],
  StakingReserved: ['投票冻结', 'Staking Reserved'],
  UnfreezeReserved: ['赎回冻结', ' Unfreeze Reserved'],
  DexReserved: ['交易冻结', 'Dex Reserved'],
  TotalBalance: ['总余额', 'Total Balance'],
  GetFreeCoin: ['领币', 'Get'],
  Transfer: ['转账', 'Transfer'],
  InnerChainTransfer: ['链内转账', 'Transfer'],
  OriginalChain: ['原链', 'Original Chain'],
  OriginalChainAddr: ['原链地址', 'Original Chain Addr'],
  WithdrawalReserved: ['提现冻结', 'Withdrawal Reserved'],
  Deposit: ['充值', 'Deposit'],
  CrossChainDeposit: ['跨链充值', 'Deposit'],
  Withdraw: ['提现', 'Withdraw'],
  CrossChainWithdraw: ['跨链提现', 'Withdraw'],
  Mapping: ['映射', 'Mapping'],
  CrossChainMapping: ['跨链映射', 'Mapping'],
  ReceiveAddress: ['接收人地址', 'Receive Address'],
  ReceiptAddress: ['收款地址', 'Receipt address'],
  TransferAmount: ['转账数量', 'Transfer Amount'],
  Memo: ['备注', 'Memo'],
  PublicMultiSigTrusteeAddress: ['公共多签托管地址', 'Public MultiSig Trustee Address'],
  CopyMessage: ['复制信息', 'Copy'],
  RecommendedChannelNode: ['输入推荐渠道的节点名称 (选填)', 'Recommended Channel Node (optional)'],
  GetWithdrawFee: ['收取提现手续费', 'Required Fee'],
  BindedAddress: ['已绑定地址', 'Binded Address'],
  BindNewAddress: ['绑定新地址', 'Bind new Address'],
  Label: ['标签', 'Label'],
  Password: ['密码', 'Password'],
  Chain: ['链', 'Chain'],
  Address: ['地址', 'Address'],
  ModifyLabel: ['修改标签', 'Modify Label'],
  Change: ['修改', 'Change'],
  Delete: ['删除', 'Delete'],
  DeleteNode: ['删除节点', 'Delete Node'],
  DeleteApi: ['删除Api', 'Delete Api'],
  DeleteAddress: ['删除地址', 'Delete'],
  PleaseSelect: ['请选择', 'Select'],
  Status: ['状态', 'Status'],
  NodeStatus: ['节点状态', 'Node Status'],
  HaveLinked: ['已连接', 'Linking'],
  OverTime: ['超时', 'OverTime'],
  UnLinked: ['未连接', 'UnLink'],
  HotEntity: ['热公钥', 'Hot Public Key'],
  HotPrivateEntity: ['热私钥', 'Hot private Key'],
  HotPrivateEntityPassword: ['热私钥密码', 'Password from Hot private Key'],
  ColdEntity: ['冷公钥', 'Cold Public Key'],
  ImportHotPrivateKey: ['导入热私钥', ' Import Hot Private Key'],
  SetupNode: ['设置节点', 'Setup Node'],
  Imported: ['已导入', 'Imported'],
  LockTime: ['锁定期{time}分钟', 'Lock {time}m'],
  NominationAmountAfterModified: ['修改后投票数', 'Nomination amount after modified'],
  Website: ['官网域名', 'Website'],

  BriefIntroduction: ['简介', 'Brief Introduction'],
  Participate: ['参选', 'Participate'],
  ParticipateStatus: ['参选状态', 'Participate Status'],
  Elect: ['退选', 'Elect'],
  IHaveRead: ['我已阅读', 'I Have Read'],
  NodeDeployDocument: ['节点部署文档', 'document for deploying Node'],
  SeeNodeDeployDocument: ['查看节点部署文档', 'document for deploying Node'],
  NotSelect: ['未勾选', 'Required Select'],
  ID: ['编号', 'Number'],
  NodeAddress: ['节点地址', 'Node Address'],
  Example: ['例', 'Example'],
  NotMathTheFormat: ['不符合格式', 'Not Follow the format'],
  HotEntityNotMathHotPrivateEntity: ['热公钥与热私钥不匹配', 'Hot private Key does not match Hot Public Key'],
  YouAre: ['您当前是', 'You are'],
  Price: ['价格', 'Price'],
  Total: ['累计', 'Total'],
  Revoke: ['撤销', 'Cancel'],
  FilledAverage: ['成交均价', 'Average'],
  FilledTotal: ['成交总额', 'Total'],
  Buy: ['买入', 'Buy'],
  Sell: ['卖出', 'Sell'],
  FullFilled: ['完全成交', 'Filled'],
  PartialFill: ['部分成交', 'PartialFill'],
  Cancelled: ['已撤销', 'Cancelled'],
  PartialFillAndCanceled: ['部分成交已撤销', 'PartFill&Cancel'],
  ShowCurrentTradingPair: ['只显示当前交易对', 'Only show current pair'],
  NoOrder: ['暂无委托', 'No Orders'],
  CounterParty: ['对手方', 'counter'],
  BuyPrice: ['买入价', 'Price'],
  SellPrice: ['卖出价', 'Price'],
  BuyAmount: ['买入量', 'Amount'],
  SellAmount: ['卖出量', 'Amount'],
  PlaceOrder: ['挂单', 'Place Order'],
  CancelOrder: ['撤单', 'Cancel Order'],
  MatchingFee: ['撮合手续费', 'Matching fee'],
  TradingVolume: ['交易额', 'volume'],
  TimeSharing: ['分时', 'Time-Sharing chart'],
  Operation: ['操作', 'Operation'],
  ParamsInfo: ['参数信息', 'Params Info'],
  BitCoinFee: ['BitCoin 手续费', 'BitCoin Fee'],
  UTXONotEnoughFee: ['utxo总额不够支付手续费', 'The utxos is Insufficient payment for fee'],
  WithDrawTotalMustBiggerZero: ['提现总额应大于0', 'total balance must greater than 0'],
  NodeHasNoUTXO: ['当前节点无任何utxo', 'This node has no utxo'],
  NotSetNode: ['未设置节点', 'Not Setup Node'],
  NodeNotLink: ['节点未连接', 'This node not linking'],
  NodeLinkFail: ['节点连接失败', 'This node linked Fail'],
  NotGetNodeNetType: ['未获取到该节点的网络类型', 'Not get this node net type'],
  NotFindTrusteeAddress: ['未获取到信托地址', 'Not Found Trustee Address'],
  ResponseList: ['响应列表', 'Response List'],
  HaveSigned: ['已签名', 'Signed'],
  Sign: ['签名', 'Sign'],
  VetoedSign: ['否决', 'Veto'],
  HaveVetoedSign: ['已否决', 'Vetoed'],
  NoResponseSign: ['未响应', 'No Response'],
  CopyOriginalDataToSigned: ['复制待签原文', 'Copy Original Data to be signed'],
  RespondMultiSigWithdrawal: ['响应多签提现', 'Respond the MultiSig Withdrawal'],
  WhetherSignature: ['是否签名', 'Signature'],
  TrueSign: ['是', 'Yes'],
  FalseSign: ['否', 'No'],
  Self: ['本人', 'Self'],
  CopySuccessful: ['复制成功', 'Copy successfully'],
  ResponseOkThenDealing: [
    '响应已完成，提现处理中',
    'The response has been completed and the withdrawal process is in progress',
  ],
  TransactionHash: ['交易Hash', 'Transaction hash'],
  ComingSoon: ['敬请期待', 'ComingSoon'],
  ThisAccount: ['本账户', 'This account'],
  NetworkSetting: ['网络设置', 'Network Management'],
  SelectNetType: ['选择网络类型', 'Select Net Type'],
  NodeSetting: ['节点管理', 'Node Management'],
  APISetting: ['Api 管理', 'Api Management'],
  AddNode: ['添加节点', 'Add Node'],
  ChangeNode: ['修改节点', 'Change Node'],
  AddApi: ['添加Api', 'Add Api'],
  Type: ['类别', 'Type'],
  NetDelay: ['网络延迟', 'NetWork Delay'],
  BlockHeight: ['块高', 'Block Height'],
  SyncStatus: ['同步状态', 'Sync Status'],
  ConnectedPeers: ['连接节点数', 'Connected Peers'],
  ApiAddress: ['Api地址', 'Api Address'],
  ProvideCoreAssetData: ['提供核心资产数据', 'Providing core asset data'],
  ProvideDetailedListData: ['提供列表详情数据', 'Provide detailed list data'],
  ImportAccount: ['导入账户', 'Import Account'],
  EnsureCustomerBackUp: [
    '确保您已备份账户，否则您的账户将无法找回',
    'Ensure you have backed up the account, or your account will be unable to be restored.',
  ],
  PrimaryPassword: ['原密码', 'Old Password'],
  NewPassword: ['新密码', 'New Password'],
  TransactionSignature: ['交易签名', 'Transaction Signature'],
  NodeFee: ['节点费用', 'Node Fee'],
  higherFeeFasterPacked: ['费用越高打包速度越快', 'The higher fee, the faster to be packed'],
  RegisterNodeUnchangeable: ['', 'Unique and non-transferable after registration'],
  LatestHeightBlock: ['最新高度', 'Latest Block'],
  BlockTime: ['出块时间', 'Block Time'],
  SwitchBestNodeAuto: ['自动切换最优节点', 'Switch to the best node automatically'],
  SwitchBestApiAuto: ['自动切换最优Api', 'Switch to the best API automatically'],

  ActualWithDrawAmount: ['实际到账数量', 'Actual Amount'],
  WithdrawAmountMustOverFee: ['提现数量必须大于手续费', 'Amount must greater than fee'],
  CharacterLength: ['{length}个字符以内', 'Within {length} characters'],
  MinCharacterLength: ['最少{length}个字符长度', 'At least {length} characters'],
  MaxCharacterLength: ['不能超过{length}个字符长度', 'At most {length} characters'],
  AmountBiggerThan: ['数量必须大于{one}', 'must greater than {one}'],
  AddressFormatError: ['地址格式错误', 'Address format error'],
  BalanceNotEnough: ['余额不足', 'Balance not enough'],
  AmountNotEnough: ['数量不足', 'not enough'],
  Required: ['必填', 'Required'],
  Confirm: ['确定', 'Confirm'],
  ConfirmPassword: ['确认密码', 'Confirm password'],
  RepeatPassword: ['重复输入密码', 'Repeat password'],
  InputPassword: ['输入密码', 'Input password'],
  PasswordNotEqual: ['密码不一致', 'Passwords does not match! '],
  PasswordError: ['密码错误', 'Password error'],
  Cancel: ['取消', 'Cancel'],
  Skip: ['跳过', 'Skip'],
  MaxPrice: ['最高', 'Max'],
  MinPrice: ['最低', 'Min'],
  TradingVolumeTooSmall: ['交易额太小', 'too small'],
};

export const zh_CN = {};
export const en_US = {};
Object.getOwnPropertyNames(zh_en).forEach(key => {
  zh_CN[key] = zh_en[key][0];
  en_US[key] = zh_en[key][1];
});
